### ISSUE TITLE
Uncaught TypeError: useDragDropContext is not a function or its return value is not iterable at createPointerSensor

### ISSUE THREAD

**Issue by jullury** [thisbeyond/solid-dnd#78]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/90042495/213773440-a27bb74c-156d-4b4d-b7e1-aa41fb39ed6b.png">

I just copied the example Board from the web site, but using typescript
my dependencies are:
   "@thisbeyond/solid-dnd": "^0.7.3",
    "solid-js": "~1.6.9",

**Comment by martinpengellyphillips** [comment]
This is usually due to vite/solid issue. Check out #67 and #53 to see if that helps.

**Comment by jullury-diris** [comment]
So there is no solution if i want to use the latest version of solid with solid-dnd? Because I am using a monorepo that all use the latest version of solid

**Comment by martinpengellyphillips** [comment]
solid-dnd works with solidjs 1.5 and greater (as per the package.json declaration). The issue you are experiencing is likely more due to your build / dev / vite setup than incompatibility between solid-dnd and solidjs. For example, the https://solid-dnd.com website source is [here](https://github.com/thisbeyond/solid-dnd-site) and you can see it using the latest solidjs 1.6 without issue.

Have you tried the suggested fix in the issues I referenced?

**Comment by jullury-diris** [comment]
Tomorrow, i'll try to create an empty project to see if the example in the works with typescript and the fix showed above.
I tried adding the optimise option but it lead me to another error unrelated with my topic

**Comment by jullury-diris** [comment]
@martinpengellyphillips this is my vite.config.js
`import { defineConfig } from 'vite'
import solidPlugin from 'vite-plugin-solid'

export default defineConfig({
  plugins: [solidPlugin()],
  optimizeDeps: {
    extensions: ['jsx','tsx'],
  },
  css: {
    modules: {
      scopeBehaviour: 'global',
    },
  },
  server: {
    port: 3000,
  },
})
`

**Comment by jullury-diris** [comment]
and this is my package.json

`{
  "name": "ui",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "lint": "eslint --cache --fix ."
  },
  "dependencies": {
    "@tailwindcss/typography": "0.*",
    "@thisbeyond/solid-dnd": "^0.7.3",
    "chart.js": "3.*",
    "chartjs-plugin-datalabels": "2.*",
    "class-variance-authority": "0.*",
    "core": "workspace:*",
    "daisyui": "^2.47.0",
    "solid-forms": "^0.4.8",
    "solid-icons": "^1.0.4",
    "solid-js": "^1.5",
    "ts-pattern": "4.*"
  },
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "autoprefixer": "10.*",
    "babel-preset-solid": "^1.6.9",
    "cssnano": "5.*",
    "eslint-config-custom": "workspace:*",
    "postcss": "8.*",
    "tailwindcss": "3.*",
    "tsconfig": "workspace:*",
    "vite": "^4.0.4",
    "vite-plugin-solid": "^2.5.0"
  }
}`

**Comment by jullury-diris** [comment]
i have successfully built my project using "vite build" and the drag and drop is work but when I'm using vite dev ("vite"), I have an error saying "React is undefined", that is weird
any clue please!

**Comment by jullury-diris** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/90042495/213992356-928c51b2-0e3f-4943-aa37-debc6b4bf7d7.png">

**Comment by martinpengellyphillips** [comment]
I think I saw something about that on the solidjs discord channel - might be worth asking there?

Other things might be to check which version of vite-plugin-solid you have - I see a few references to a react undefined error in the [issues](https://github.com/solidjs/vite-plugin-solid/issues?q=is%3Aissue+react+) there.

**Comment by Supertigerr** [comment]
Same error. Any fix?

**Comment by martinpengellyphillips** [comment]
Please provide a link to the repository demonstrating the error. Otherwise there are too many variables to consider (most of which are unrelated to solid-dnd itself).

**Comment by Supertigerr** [comment]
I mean, I install the package, I copy one of the examples, I get error. Idk what to say. I can set up an example in a bit

**Comment by Supertigerr** [comment]
https://stackblitz.com/edit/github-sadxvo?file=src%2FApp.tsx

**Comment by Supertigerr** [comment]
seems like adding:
```ts
  optimizeDeps: {
    extensions: ['jsx'],
  },
  ```
  to `vue.config.ts` does indeed fix this, but its not ideal is it. No other packages have this problem

**Comment by martinpengellyphillips** [comment]
Which other packages are you referring to? Perhaps we can learn something from their setup?

**Comment by frnsys** [comment]
I'm having the same issue--I copied over the vertical sortable example from <https://solid-dnd.com/> and get the error: `TypeError: null is not an object (evaluating 'useDragDropContext()')`. Using:

```
    "solid-js": "^1.6.9",
    "@thisbeyond/solid-dnd": "^0.7.3",

    "vite": "^4.0.4",
    "vite-plugin-solid": "^2.5.0"
```

I can confirm that adding:

```
  optimizeDeps: {
    extensions: ['jsx'],
  },
```

to my `vite.config.js` also fixes it for me.

**Comment by martinpengellyphillips** [comment]
Looks like #80 will fix this when merged.

**Comment by martinpengellyphillips** [comment]
#80 is now released as [0.7.4](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.4) and this issue should no longer occur (nor require the workaround).

**Comment by gawlk** [comment]
Hi,

Is it possible that there was a regression ?

I also have the issue with everything up to date, while trying the vertical example 

![Screenshot 2023-06-20 at 14 01 32](https://github.com/thisbeyond/solid-dnd/assets/32246972/2a2f5267-2af2-49d2-8476-31c7337e6e1b)

**Comment by martinpengellyphillips** [comment]
I wonder if this is a recent solidjs update causing it?

**Comment by gawlk** [comment]
@martinpengellyphillips Mmmh just tried the example with a new Solid template with everything up to date and there is no issue. Everything seems to work as intended.

I'll have to dig deeper to find the problem.

I'll post here if it's from `solid-dnd`

**Comment by gawlk** [comment]
I was refactoring and the error was because I forgot to re-add the parent component from the example, my bad !
